@startuml
title UC-10: Списать баллы по программе лояльности
actor "Пользователь" as U 
participant  "Приложение" as A 
boundary "Сервис заказа" as S
dataBase "База данных" as DB 
autonumber "<b>[0]" 

ref over U,A,S,DB
UC-4: Сформировать корзину
end ref

U->A++: Списать баллы
A->S++: Списать баллы
S->DB++: Проверить наличие баллов
alt Баллы есть на счете
DB-->S:Баллы есть на счете
S->S++: Выполнить расчет полей \n"Списано" и "Итого со скидкой" 
S--
S-->A: Отправить "Списано баллов"
S-->A: Отправить "Итого с учетом скидки"
A-->U: Отобразить поля
alt Оплатить заказ
ref over U,A,S, DB
UC-7: Произвести оплату картой
end ref
S->DB: Выполнить списание \nбонусных баллов 
DB-->S: Ответ
S->DB: Выполнить начисление \nбонусных баллов 
DB-->S: Ответ
else Удалить списание
U->A: Назад
A->A++: Открыть страницу  \n"Времени приготовления блюд"
A--
A->S: Отменить расчет полей \n"Списано" и "Итого со скидкой" 
A->A++: Удалить кеш со страницы \nоплаты заказа
A--
end
else  Баллы отсутствуют
DB-->S:Баллы отсутствуют
DB--
S-->A: Ответ
A-->U: Уведомление
end
S--
A--
@enduml
