@startuml
title UC-14: Добавление КомбоБургера
actor "Пользователь" as U 
participant  "Приложение" as A 
boundary "Сервис заказа" as S
dataBase "База данных" as DB 
autonumber "<b>[0]"  

ref over U,A,S,DB
UC-2: Авторизация пользователя в системе
end ref

alt количество блюд в корзине < 28
loop Пока корзина не сформирована 
U->A++: Добавить блюдо 
A->S++: Добавить блюдо во временный заказ
S->S++: Расчитать стоимость заказа
S-->A--:Ответ
A-->U: Отобразить добавления
end
else количество блюд в корзине = 29
U->A: Добавить блюдо 
A->S: Добавить блюдо во временный заказ
S->S++: Расчитать стоимость заказа
S-->A:Деактивировать кнопки добавления
S--
A->A++: Деактивировать кнопки добавления
A--
A->U: Кнопка добавления не активна
A->U: Отправить уведомление \nпользователю
end

opt добавления КомбоБургера в корзину
U->A: Добавить КомбоБургер 
A->S: Добавить блюдо во временный заказ
S->S++: Создать новый рецепт
S-->A--:Отправить список и \nколичество допустимых \nингредиентов для КомбоБургера  
A-->U: Отобразить добавления \nКомбоБургера

loop Пока не сформирован КомбоБургер 
U->A: Добавить/удалить ингредиент 
A->S: Добавить/удалить ингредиент в рецепте
S->S++: Расчитать стоимость заказа
S-->A--:Ответ
A-->U: Отобразить \nдобавления/удаления
end
end

U->A: Перейти в корзину 
A->S: Перейти в корзину
S->S++: Расчет суммы 
S--
S-->A:Ответ
A-->U: Отобразить добавления
alt Удаление блюда из корзины
loop Пока корзина не сформирована 
U->A: Удалить блюдо 
A->S: Удалить блюдо из временного заказа
S->S++: Расчитать стоимость заказа
S-->A--:Ответ
A-->U: Отобразить изменение
end
else  Очистка корзины
U->A: Очистить корзину 
A->S: Удалить временный заказ
S->S++: Обнулить стоимость заказа
S-->A--: Деактивировать кнопку "Оформить заказ"
A->A++: Деактивировать кнопку "Оформить заказ"
A-->U: Отобразить изменение
A--
S--
end

@enduml
