@startuml
title UC-11: Получить информацию о готовности заказа на информационном табло
actor "Пользователь" as U 
actor "Менеджер \nна гостеприимстве" as M  
boundary "Сервис заказа" as S
boundary "Сервис управления \nготовности заказа" as BOARD
dataBase "База данных" as DB 
autonumber "<b>[0]" 

U->BOARD++: Просматривает

alt Заказ готов
BOARD->DB++: Проверка статуса 
return Статус: "Готов"
BOARD-->U:Заказ готов к выдаче

else  Заказ не готов
BOARD->DB++: Проверка статуса 
DB-->BOARD--: Статус: "Готовится" 
BOARD-->U:Заказ готовится

else  Заказ отсутствует на информационном табло
BOARD-->U:Заказ отсутствует на информационном табло
U->M++: Уточнение статуса заказа
M->S++: Уточнение статуса заказа
S->DB++: Уточнение статуса заказа
return Ответ
return Ответ
return Ответ
BOARD--
end
@enduml
