@startuml
title UC-1: Регистрация пользователя в системе
actor "Пользователь" as U 
participant  "Приложение" as A 
boundary "Сервис регистрации" as S
boundary "Сервис отправки SMS" as SMS
dataBase "База данных" as DB 
autonumber "<b>[0]"  

U->A++: Открыть страницу регистрации
return Ответ
U->A++: Передать регистрационную информацию
A->A++: Проверка корректности заполненных полей
A--
alt Информация заполнена не корректно
A-->U:Уведомление о некорректности информации
else  Информация заполнена корректно
A->S++: Валидация информации
S->DB++: Валидация информации
alt Успешная регистрация
S--
DB-->S++: Валидация прошла успешно
S-->S++: Сгенерировать SMS
S--
S-->SMS++: Передать SMS код
SMS-->U--: Код подтверждения
S-->A: Запросить код подтверждения
S--
A-->U: Запросить код подтверждения

alt Код подтверждения введен успешно
U->A: Ввести код подтверждения
A->S++: Код подтверждения
S->S++: Подтверждение
S--
S->DB: Добавить клиента
DB-->S: Клиент добавлен
S-->A: Успешная регистрация
S--
A-->U: Успешная регистрация
A->A++:Перенаправление на целевую страницу
A--
else Код введен с ошибкой
U->A: Ввести код подтверждения
A->S++: Код подтверждения
S->S++: Ошибка кода подтверждения
S--
S-->A: Уведомление об ошибке
S--
A-->U: Уведомление об ошибке
else Код не получен
loop Повторно отправить SMS
U->A: Запросить отправку SMS
A->S++: Запросить отправку SMS
S-->S++: Сгенерировать SMS
S--
S-->SMS++: Передать SMS код
SMS-->U--: Код подтверждения
S--
end
end
else Номер телефона существует в системе
DB-->S++: Номер телефона найден
S-->A: Ошибка регистрации
S--
A-->U: Ошибка регистрации
else E-mail существует в системе
DB-->S++: E-mail найден
DB--
S-->A: Ошибка регистрации
S--
A-->U: Ошибка регистрации
A--
end
end
@enduml
