@startuml
title UC-2: Авторизация пользователя в системе
actor "Пользователь" as U 
participant  "Приложение" as A 
boundary "Сервис аутентификации" as S
dataBase "База данных" as DB 
autonumber "<b>[0]"  

U->A++: Открыть страницу авторизации
return Ответ
U->A++: Передать данные для авторизации
A->A++: Проверка корректности заполненных полей
alt Информация заполнена не корректно
A-->U:Уведомление о некорректном заполнении
else  Информация заполнена корректно
A--
A->S++: Отправить логин и пароль
A--
S->S++: Сгенерировать хеш пароля
S--
S->DB++: Проверить логин/пароль
S--
alt Успешная аутентификация
DB-->S++: Успешно
S->S++: Сгенерировать токен
S--
S-->A++: Отправить токен
S--
A->A++: Отправить токен
A--
A--
else Аутентификация не пройдена
DB-->S++: Пользователь не найден
DB--
S-->A++:Сообщение об ошибке
S--
A-->U: Уведомить об ошибке 
A--
end
end
@enduml
