@startuml
title UC-4: Сформировать корзину
actor "Пользователь" as U 
participant  "Приложение" as A 
boundary "Сервис заказа" as S
dataBase "База данных" as DB 
autonumber "<b>[0]"  

ref over U,A,S,DB
UC-2: Авторизация пользователя в системе
end ref

alt количество блюд в корзине < 99
loop Пока корзина не сформирована 
U->A++: Добавить блюдо 
A->S++: Добавить блюдо во временный заказ
S->S++: Расчитать стоимость заказа
S-->A--:Ответ
A-->U: Отобразить добавления
end
else количество блюд в корзине >= 99
S-->A:Ответ
A->A++: Деактивировать кнопок добавления
A--
A->U: Кнопка добавления не активна
end

U->A: Перейти в корзину 
A->S: Перейти в корзину
S->S++: Расчет суммы 
S--
S-->A:Ответ
A-->U: Отобразить добавления

opt Удаление блюда из корзины
loop Пока корзина не сформирована 
U->A: Удалить блюдо 
A->S: Удалить блюдо из временного заказа
S->S++: Расчитать стоимость заказа
S-->A--:Ответ
A-->U: Отобразить изменение
A--
S--
end
end

@enduml
