@startuml
title UC-7: Оплата заказа картой
actor "Пользователь" as U 
participant  "Приложение" as A 
boundary "Сервис заказа" as S
boundary "Сервис управления \nоплатой" as BK
boundary "Сервис управления \nРоботами" as ROBERT
boundary "Сервис управления \nготовности заказа" as BOARD
boundary "Почтовый сервис" as EMAIL
dataBase "База данных" as DB 
autonumber "<b>[0]" 

U->A++: Оплата заказа
A->S++: Оплата заказа 
S->BK++: Оплата заказа 
BK-->A: Запрашивает данные карты
A-->U: Форма для заполнения
U->A: Ввод данных карты оплаты
A->A++: Проверка корректности заполненных полей
A--
alt Информация заполнена не корректно
A-->U:Уведомление о некорректности информации
else  Информация заполнена корректно
A->S: Отравляет данные карты
A--
S->BK: Отравляет данные карты \nи сумму к оплате
BK->BK++: Проверяет данные карты \nи сумму к оплате
BK--

alt Оплата произведена успешно
BK-->S: Подтверждение оплаты
S->S++: Удаление временного заказа
S--
S->DB++: Создание заказа
return Ответ
S->EMAIL++: Электронный кассовый чек
note left of EMAIL
 E-mail указанный пользователем при регистрации 
end note
return Ответ
S->ROBERT++: Передача заказа в производство
return Ответ
S->BOARD++: Отображение заказа на табло
return Ответ
S-->A++: Уведомление успешной оплаты
A-->U: Подтверждение успешной оплаты и чек
A-->U: Получение номера заказа
A--
else  Недостаточно денежных стредств
BK-->S: Уведомление о недостаточности \nденежных средств
S-->A++: Уведомление об ошибке
A-->A++: Возврат на страницу оплаты
A--
A-->U: Уведомление об ошибке
A-->U: Возврат на страницу оплаты
else  Ошибка оплаты
BK-->S: Уведомление об ошибке оплаты 
S-->A: Уведомление об ошибке
A-->A++: Возврат на страницу оплаты
A--
A-->U: Уведомление об ошибке
A-->U: Возврат на страницу оплаты
BK--
S--
A--
end
end
@enduml
