@startuml
title Модель предметной области

Entity Пользователь 
{
ФИО
Дата рождения
Пол
Телефон
E-mail
Пароль
}


Entity Меню {
Наименование
Категория меню
Срок действия
}

Entity Блюдо {
Наименование
Категория
Б
Ж
У
Калорийность
Описание
Фотография
Рецепт
Скидка
Цена
Связанные блюда
}

Entity Рецепт {
Наименование Рецепта
Наименование Ингредиента
Количество
Максималльное количество ингредиента
Минимальное количество ингредиента
Обязательность
Б
Ж
У
Калорийность

}

Entity Корзина {
Блюдо
Количество
Стоимость
}

Entity Комбобургер {
Наименование
Наценка
}

Entity Ингредиент {
Наименование
Б
Ж
У
Калорийность
Фотография
Количество
Партия
Резерв
Цена
Срок годности
}

Entity Закуп {
Номер Заказа
Дата_время
Наименование Ингредиента
Количество
Требуемая дата
}

Entity Заказ {
Номер Заказа
Дата_время
Статус
Способ получения
Дата_время получения
Оплата 
Скидка
Итог
}

Entity Оплата{
Номер оплаты
Способ оплаты
Дата_время
Сумма
}

Entity Бонусы{
Тип Бонусов
Начисление/Списание бонусов
Коэффициент цены бонусов
Итого бонусов
Дата_время
Срок годности бонусов
}

Entity Наличные{
Купюра
Количество купюр
Итого наличных
Дата_время
}

Entity "Оплата Картой"{
Банк
Идентификатор платежа
Итого
Дата_время
}


Пользователь "1  " -->  "0..*  " Заказ: Оформляет
Пользователь " 0..1 " -->  " 0..1" Корзина: Формирует

Заказ ^-- Корзина 
Заказ "0..1 " o-- "0..1 " Оплата 
Оплата ^-- Бонусы 
Оплата ^-- Наличные
Оплата ^-- "Оплата Картой"
Блюдо "1..*" --o " 0..1  " Корзина
Комбобургер --^ Блюдо
Меню "1..*" o- "1..*" Блюдо 
Рецепт "1..* "  --o "1..* " Комбобургер
Ингредиент -- Ингредиент
Блюдо --o Блюдо
Блюдо "1..*  "  o-- "1..*"  Рецепт
Рецепт "1..*  " o-- "2..10" Ингредиент
Ингредиент "1..*" --o "1..*  "Закуп    
@enduml